blueprint:
  name: AQI notification for all window sensors
  description: Warn if a window is open and the AQI is above some threshold.
  domain: automation
  input:
    warn_threshold:
      name: AQI warn threshold
      description: Warn about AQI when above this threshold (0-500).
      default: 50
      selector: &threshold_selector
        number:
          min: 0
          max: 500
          mode: box
    critical_threshold:
      name: AQI critical threshold
      description: Critical when AQI when above this threshold (0-500).
      default: 100
      selector: *threshold_selector
    windows:
      name: Window(s)
      description: Window to trigger on. This can be a group.
      selector:
        entity:
          domain: binary_sensor

variables:
  warn_threshold: !input "warn_threshold"
  critical_threshold: !input "critical_threshold"
  aqi: "{{ states('sensor.airnow_aqi') }}"

trigger:
  - platform: state
    entity_id: !input "windows"
    to: "on"
condition:
  - "{{ int(states('sensor.airnow_aqi')) > warn_threshold }}"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ aqi >= warn_threshold and aqi < critical_threshold }}"
        sequence:
          - service: notify.all_phones
            data:
              title: ⚠️ Air Quality Warning ⚠️
              message: >-
                AQI is {{aqi}} which is above your warn threshold of
                {{warn_threshold}}.
      - conditions:
          - condition: template
            value_template: "{{ aqi >= critical_threshold }}"
        sequence:
          - service: notify.all_phones
            data:
              title: ‼️ Air Quality Critical ‼️
              message: >-
                AQI is {{aqi}} which is above your critical threshold of
                {{critical_threshold}}.
    default: []
mode: single
